# Generated by Django 4.2.7 on 2024-01-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='twitter',
            field=models.CharField(default='xfgsf', max_length=50),
            preserve_default=False,
        ),
    ]
