# Generated by Django 4.2.7 on 2024-01-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_avatar_alter_contact_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
